basePath: /
definitions:
  apis.ChangePasswordRequest:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    type: object
  apis.LoginRequest:
    properties:
      login:
        description: username hoặc email
        type: string
      password:
        type: string
    type: object
  apis.Profile:
    properties:
      avatar:
        type: string
      bio:
        type: string
      createdAt:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
  apis.ProfileUpdate:
    properties:
      avatar:
        type: string
      bio:
        type: string
      username:
        type: string
    type: object
  apis.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample Swagger API with net/http
  title: Swagger with net/http
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login using username or email
      parameters:
      - description: Login data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/apis.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new account
      parameters:
      - description: Register data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/apis.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - auth
  /me:
    delete:
      description: Mark account as deleted
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Soft delete current account
      tags:
      - auth
    patch:
      consumes:
      - application/json
      description: Update avatar, username, or bio
      parameters:
      - description: Profile update data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/apis.ProfileUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: 'message: Profile updated'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 'error: Invalid data'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update own profile
      tags:
      - profile
  /me/password:
    put:
      consumes:
      - application/json
      description: Change password for the current user
      parameters:
      - description: Password data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/apis.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Change password
      tags:
      - auth
  /username/:
    get:
      description: return list of usernames
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Get all usernames
      tags:
      - username
    post:
      consumes:
      - application/json
      description: add a username to list
      parameters:
      - description: Username JSON
        in: body
        name: username
        required: true
        schema:
          additionalProperties:
            type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: added successfully
          schema:
            type: string
      summary: Add new username
      tags:
      - username
  /users:
    get:
      description: Search users by query with pagination and sorting
      parameters:
      - description: Search query
        in: query
        name: search
        type: string
      - description: Offset
        in: query
        name: offset
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Sort by field
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: users list and total count
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'error: Invalid parameters'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search users
      tags:
      - profile
  /users/{user_id}:
    get:
      description: Get profile by user_id (may require auth for private profiles)
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apis.Profile'
        "403":
          description: Private profile
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user profile
      tags:
      - profile
swagger: "2.0"
