basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample Swagger API with net/http
  title: Swagger with net/http
  version: "1.0"
paths:
  /username/:
    get:
      description: return list of usernames
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Get all usernames
      tags:
      - username
    post:
      consumes:
      - application/json
      description: add a username to list
      parameters:
      - description: Username JSON
        in: body
        name: username
        required: true
        schema:
          additionalProperties:
            type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: added successfully
          schema:
            type: string
      summary: Add new username
      tags:
      - username
swagger: "2.0"
